import os
from google.adk.models.lite_llm import LiteLlm
import streamlit as st
from datetime import datetime


OPENAI_API_KEY = os.environ.get("OPENAI_AGENTS_API_KEY")

MODEL = "gemini-2.5-flash"
# MODEL = LiteLlm('openai/gpt-4o-mini', api_key=OPENAI_API_KEY)
SEARCH_AGENT_MODEL = "gemini-2.5-flash-lite"
CREATIVES_AGENT_MODEL = "gemini-2.5-flash"


def get_user_email():
    return st.user.get("email", "Unknown User")


def get_username():
    return st.user.get("name", "Unknown User")


def get_username_str():
    return (
        f"The user's name is {get_username()}."
        if get_username() != "Unknown User"
        else "The user's name is not available."
    )


def get_current_datetime():
    """A helper function used to retrieve current date and time. Use it when you need to be time-aware."""
    return datetime.now()


table_data = {
    "auxillary_development.all_order_report": "A table with all orders information for Amazon, including off-amazon sales which were fulfilled by Amazon",
    "auxillary_development.amazon_fulfilled_orders": "Amazon fulfilled orders (excluding FBM shipments), crucial table for building a Promotions report",
    "auxillary_development.attribution": "",
    "auxillary_development.dashboard": "",
    "auxillary_development.dictionary": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for USA",
    "auxillary_development.dictionary_ca": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for Canada",
    "auxillary_development.dictionary_eu": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for Europe",
    "auxillary_development.dictionary_shp": "A mapping table (dictionary), containing all the necessary SKU mapping data for Shopify",
    "auxillary_development.dictionary_uk": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for United Kingdom",
    "auxillary_development.dictionary_wm": "A mapping table (dictionary), containing all the necessary SKU mapping data for Walmart",
    "auxillary_development.dimensions": "",
    "auxillary_development.inventory_report": "",
    "auxillary_development.keywords_de": "",
    "auxillary_development.keywords_fr": "",
    "auxillary_development.keywords_uk": "",
    "auxillary_development.keywords_us": "",
    "auxillary_development.matt": "",
    "auxillary_development.price_comparison": "",
    "auxillary_development.promotions": "",
    "auxillary_development.restock_inventory": "",
    "auxillary_development.reviews_us": "",
    "auxillary_development.scp_asin_weekly": "",
    "auxillary_development.sku_changelog": "A changelog containing all the records for changes that could impact sales performance (per SKU) for USA Amazon",
    "auxillary_development.sku_changelog_ca": "A changelog containing all the records for changes that could impact sales performance (per SKU) for Canada Amazon",
    "auxillary_development.sku_changelog_de": "",
    "auxillary_development.sku_changelog_es": "",
    "auxillary_development.sku_changelog_fr": "",
    "auxillary_development.sku_changelog_it": "",
    "auxillary_development.sku_changelog_uk": "",
    "auxillary_development.sqp_brand_weekly": "",
    "clickup.active_projects_tasks": "",
    "clickup.active_spaces_tasks": "",
    "clickup.clickup_tasks": "",
    "clickup.clickup_tasks_hist": "",
    "clickup.projects_statuses": "",
    "clickup.spaces_statuses": "",
    "clickup.tasks_report": "",
    "clickup.tasks_report_hist": "",
    "daily_reports.pricelist": "",
    "daily_reports.restock": "",
    "ds_for_bi.abc_analysis_dumps": "",
    "ds_for_bi.ad_internal_amz": "",
    "ds_for_bi.ad_internal_amz_api": "",
    "ds_for_bi.amazon_attribution_tags": "",
    "ds_for_bi.amazon_attribution_view": "",
    "ds_for_bi.amazon_creators": "",
    "ds_for_bi.amazon_daily": "",
    "ds_for_bi.amz_sales_deviation_180d": "",
    "ds_for_bi.ana_data": "",
    "ds_for_bi.aspire_manual_samples": "",
    "ds_for_bi.bq_table_meta_data": "",
    "ds_for_bi.check": "",
    "ds_for_bi.classified_reviews": "",
    "ds_for_bi.cogs": "",
    "ds_for_bi.cogs_calculation_gsheet": "",
    "ds_for_bi.cogs_calculations_results": "",
    "ds_for_bi.cogs_calulation_data": "",
    "ds_for_bi.container_processing_collections_pivot": "",
    "ds_for_bi.container_processing_view": "",
    "ds_for_bi.container_processing_view_old": "",
    "ds_for_bi.creators_connections_rep": "",
    "ds_for_bi.creators_pivot_view": "",
    "ds_for_bi.daily_targets": "",
    "ds_for_bi.daily_targets_high_level": "",
    "ds_for_bi.date_range_all_countries": "",
    "ds_for_bi.date_range_business_report": "",
    "ds_for_bi.date_range_depr_view": "",
    "ds_for_bi.date_range_report_test": "",
    "ds_for_bi.date_range_summary_v2": "",
    "ds_for_bi.deals_group": "",
    "ds_for_bi.dictionary": "",
    "ds_for_bi.dictionary_fbm_missed": "",
    "ds_for_bi.dictionary_inv_statuses_hist": "",
    "ds_for_bi.dictionary_items_in_box": "",
    "ds_for_bi.driven_promo_revenue": "",
    "ds_for_bi.driven_promo_view": "",
    "ds_for_bi.dsp_direct_spend": "",
    "ds_for_bi.dsp_total_spend": "",
    "ds_for_bi.events_calendar": "",
    "ds_for_bi.fba_inv_missed_dates": "",
    "ds_for_bi.fba_inventory_partitioned": "",
    "ds_for_bi.fba_storage_fees_calculation_data": "",
    "ds_for_bi.flags_iso": "",
    "ds_for_bi.giveaway_expenses": "",
    "ds_for_bi.giveaway_revenue": "",
    "ds_for_bi.influencers_expenses": "",
    "ds_for_bi.large_orders": "",
    "ds_for_bi.ld_order_details": "",
    "ds_for_bi.ld_order_details_all_orders": "",
    "ds_for_bi.lightning_deals": "",
    "ds_for_bi.lightning_deals_report": "",
    "ds_for_bi.lightning_deals_view": "",
    "ds_for_bi.lost_prevented_overstock_products": "",
    "ds_for_bi.lost_sales": "",
    "ds_for_bi.lost_sales_full_data": "",
    "ds_for_bi.lost_sales_hist": "",
    "ds_for_bi.lost_sales_v2": "",
    "ds_for_bi.lost_sales_v3_data": "",
    "ds_for_bi.maverickx_daily": "",
    "ds_for_bi.meta_fb_posts_hist": "",
    "ds_for_bi.meta_fb_posts_hist_2": "",
    "ds_for_bi.meta_instagram_post_hist": "",
    "ds_for_bi.overstock_products": "",
    "ds_for_bi.performance_summary": "",
    "ds_for_bi.pivot_sales_180d_by_ch": "",
    "ds_for_bi.prices_history": "",
    "ds_for_bi.product_cost_hist": "",
    "ds_for_bi.sales_and_returns_allorders_view": "",
    "ds_for_bi.samples_pivot": "",
    "ds_for_bi.samples_provided_to_influencers": "",
    "ds_for_bi.samples_with_shipping_cost": "",
    "ds_for_bi.scorecard_general_measures": "",
    "ds_for_bi.sellecloud_transit_to_wh": "",
    "ds_for_bi.storage_fees_addition": "",
    "ds_for_bi.storage_fees_amz_estim_and_plan": "",
    "ds_for_bi.storage_fees_fba_inv_planning": "",
    "ds_for_bi.storefront_insights_view": "",
    "ds_for_bi.storefront_pages_mapper": "",
    "ds_for_bi.target_wos_by_sku": "",
    "ds_for_bi.targets": "",
    "ds_for_bi.targets_calc": "",
    "ds_for_bi.targets_calc_all_channels": "",
    "ds_for_bi.tiktok_orders": "",
    "ds_for_bi.update_freq_norms": "",
    "ds_for_bi.walmart_restock": "",
    "ds_for_bi.walmart_restock_2": "",
    "ds_for_bi.zendesk": "",
    "ebay.orders": "",
    "ebay.payout": "",
    "ebay.promoted_listings_general": "",
    "ebay.promoted_listings_priority": "",
    "ebay.transactions": "",
    "facebook.attribution_facebook": "",
    "facebook.facebook_posts": "",
    "facebook.facebook_posts_copy": "",
    "facebook.insights": "",
    "facebook.instagram_posts": "",
    "google.ads_report": "",
    "google.conversions_report": "",
    "google.google_vs_pinterest": "",
    "google.google_vs_pinterest_": "",
    "hurma.candidates": "",
    "hurma.careers": "",
    "hurma.clickup_candidates": "",
    "hurma.clickup_contact_list": "",
    "hurma.clickup_job_posting": "",
    "hurma.clickup_pto_calendar": "",
    "hurma.departments": "",
    "hurma.employees": "",
    "hurma.employees_archive": "",
    "hurma.out_off_office": "",
    "hurma.stages": "",
    "hurma.teams": "",
    "hurma.temp_workers": "",
    "hurma.temp_workers_pb": "",
    "hurma.tenure": "",
    "hurma.vacancies": "",
    "klaviyo.campaign_values": "",
    "klaviyo.campaigns_details": "",
    "klaviyo.flow_series": "",
    "kustomer.diff_report": "",
    "levanta.brands": "",
    "levanta.brb_reports": "",
    "levanta.click_reports": "",
    "levanta.creators": "",
    "levanta.products": "",
    "levanta.summary_performance": "",
    "levanta.test_groups": "",
    "lookerstudio_ds.ana_meta_tracker": "",
    "lookerstudio_ds.meta_marketing_insights": "",
    "pinterest.ads_analytics": "",
    "reports.AdvertisedProduct": "",
    "reports.PurchasedProduct": "",
    "reports.SponsoredBrandsPlacement": "",
    "reports.SponsoredDisplay": "",
    "reports.SponsoredProductsPlacement": "",
    "reports.active_listing_report": "",
    "reports.aged_inventory_surcharge": "",
    "reports.all_listing_report": "",
    "reports.all_orders": "",
    "reports.all_orders_usd": "",
    "reports.attribution": "",
    "reports.awd_inventory": "",
    "reports.awd_shipments": "",
    "reports.awd_shipments_details": "",
    "reports.business_report": "",
    "reports.business_report_asin": "",
    "reports.date_range_report": "",
    "reports.dictionary": "",
    "reports.dsp_report": "",
    "reports.exchange_rates": "",
    "reports.fba_inventory": "",
    "reports.fba_inventory_partitioned": "",
    "reports.fba_inventory_planning": "Main table containing all necessary inventory information for multiple Amazon marketplaces",
    "reports.fba_inventory_planning_copy": "",
    "reports.fba_returns": "",
    "reports.fee_preview": "",
    "reports.fee_preview_usd": "",
    "reports.fulfilled_inventory": "",
    "reports.inventory": "",
    "reports.profitability": "",
    "reports.profitability_view": "",
    "reports.promotions": "",
    "reports.reserved_inventory": "",
    "reports.restock_inventory": "",
    "reports.settlement": "",
    "reports.settlement_daily": "",
    "reports.settlement_daily_usd": "",
    "reports.shipments": "",
    "reports.sponsored_brands_all": "",
    "reports.sponsored_brands_video": "",
    "reports.sponsored_display": "",
    "reports.storage_fee": "",
    "reports.storage_fee_usd": "",
    "reports.store_insights_asin": "",
    "reports.store_insights_date": "",
    "reports.store_insights_pages": "",
    "sellercloud.fba_shipments": "",
    "sellercloud.fba_shipments_partitioned": "",
    "sellercloud.inventory": "",
    "sellercloud.inventory_bins": "",
    "sellercloud.inventory_bins_partitioned": "",
    "sellercloud.inventory_bins_report": "",
    "sellercloud.inventory_partitioned": "",
    "sellercloud.orders": "",
    "sellercloud.purchase_orders": "",
    "sellercloud.purchase_orders_saved_and_pending": "",
    "sellercloud.warehouse_bin_movements": "",
    "shipstation.samples_shipments": "",
    "shipstation.samples_shipments_cost": "",
    "shipstation.shipstation_orders": "",
    "shipstation.shipstation_orders_temp": "",
    "shipstation.shipstation_shipments": "",
    "shipstation.shipstation_stores": "",
    "shipstation.shipstation_tags": "",
    "shopify.abandoned_checkouts": "",
    "shopify.customers": "",
    "shopify.ebay_vs_shopify": "",
    "shopify.inventory": "",
    "shopify.ordered_products": "",
    "shopify.orders": "",
    "skai.campaigns_info": "",
    "skai.campaigns_performance": "",
    "skai.campaigns_performance_v2": "",
    "slack.users_list": "",
    "supply_chain.aged_inventory_surcharge": "",
    "supply_chain.awd_inventory": "",
    "supply_chain.awd_shipments": "",
    "supply_chain.awd_shipments_details": "",
    "supply_chain.business_report": "",
    "supply_chain.fba_inventory": "",
    "supply_chain.manage_fba_Inventory": "",
    "supply_chain.monthly_storage_fee": "",
    "supply_chain.reserved_inventory": "",
    "supply_chain.restock_inventory": "",
    "supply_chain.sellercloud_fba_shipments": "",
    "supply_chain.sellercloud_fba_shipments_partitioned": "",
    "supply_chain.sellercloud_inventory": "",
    "supply_chain.sellercloud_inventory_bins": "",
    "supply_chain.sellercloud_inventory_bins_partitioned": "",
    "supply_chain.sellercloud_inventory_partitioned": "",
    "supply_chain.sellercloud_orders": "",
    "supply_chain.sellercloud_purchase_orders": "",
    "supply_chain.sellercloud_wh_bin_movements": "",
    "target.financial_reconciliation": "",
    "target.orders": "",
    "target.returns": "",
    "target.returns_details": "",
    "tiktok.attribution_tiktok": "",
    "tiktok.campaign_metrics": "",
    "tiktok.gmv_max_metrics": "",
    "tiktok.orders": "",
    "tiktok.returns": "",
    "tiktok.sku_duplicates": "",
    "tiktok.states_dict": "",
    "tiktok.tiktok_fba_finder": "",
    "tiktok.tiktok_fin_view_bi": "",
    "tiktok.tiktok_fin_view_bi_2": "",
    "tiktok.tiktok_finance_report": "",
    "tiktok.tiktok_finance_report_2": "",
    "tiktok.tiktok_order_temp": "",
    "tiktok.tiktok_shipping": "",
    "tiktok.tiktok_shipping_cost": "",
    "walmart.inventory": "",
    "walmart.inventory_wfs": "",
    "walmart.legacy_payments": "",
    "walmart.legacy_payments_tmp": "",
    "walmart.orders": "",
    "walmart.orders_total": "",
    "walmart.payments": "",
    "walmart.payments_tmp": "",
    "walmart.returns": "",
    "walmart.summary": "",
    "zenefits.employments": "",
    "zenefits.out_off_office": "",
    "zenefits.people": "",
    "zenefits.people_and_employments": "",
}
