import os
from google.adk.models.lite_llm import LiteLlm
import streamlit as st
from datetime import datetime


OPENAI_API_KEY = os.environ.get("OPENAI_AGENTS_API_KEY")

MODEL = "gemini-2.5-flash"
# MODEL = LiteLlm('openai/gpt-4o-mini', api_key=OPENAI_API_KEY)
SEARCH_AGENT_MODEL = "gemini-2.5-flash-lite"
CREATIVES_AGENT_MODEL = "gemini-2.5-flash"


def get_user_email():
    return st.user.get("email", "Unknown User")


def get_username():
    return st.user.get("name", "Unknown User")


def get_username_str():
    return (
        f"The user's name is {get_username()}."
        if get_username() != "Unknown User"
        else "The user's name is not available."
    )


def get_current_datetime():
    """A helper function used to retrieve current date and time. Use it when you need to be time-aware."""
    return datetime.now()


table_data = {
    "auxillary_development": {
        "all_order_report": "",
        "amazon_fulfilled_orders": "",
        "attribution": "",
        "dashboard": "",
        "dictionary": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for USA",
        "dictionary_ca": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for Canada",
        "dictionary_eu": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for Europe",
        "dictionary_shp": "A mapping table (dictionary), containing all the necessary SKU mapping data for Shopify",
        "dictionary_uk": "A mapping table (dictionary), containing all the necessary ASIN and SKU mapping data for United Kingdom",
        "dictionary_wm": "A mapping table (dictionary), containing all the necessary SKU mapping data for Walmart",
        "dimensions": "",
        "inventory_report": "Old inventory table, do not use",
        "keywords_de": "",
        "keywords_fr": "",
        "keywords_uk": "",
        "keywords_us": "",
        "matt": "",
        "price_comparison": "",
        "promotions": "",
        "restock_inventory": "",
        "reviews_us": "",
        "scp_asin_weekly": "",
        "sku_changelog": "A changelog containing all the records for changes that could impact sales performance (per SKU) for USA Amazon",
        "sku_changelog_ca": "A changelog containing all the records for changes that could impact sales performance (per SKU) for Canada Amazon",
        "sku_changelog_de": "",
        "sku_changelog_es": "",
        "sku_changelog_fr": "",
        "sku_changelog_it": "",
        "sku_changelog_uk": "",
        "sqp_brand_weekly": "",
    },
    "clickup": {
        "active_projects_tasks": "",
        "active_spaces_tasks": "",
        "clickup_tasks": "",
        "clickup_tasks_hist": "",
        "projects_statuses": "",
        "spaces_statuses": "",
        "tasks_report": "",
        "tasks_report_hist": "",
    },
    "daily_reports": {"pricelist": "", "restock": ""},
    "ds_for_bi": {
        "abc_analysis_dumps": "",
        "ad_internal_amz": "",
        "ad_internal_amz_api": "",
        "amazon_attribution_tags": "",
        "amazon_attribution_view": "",
        "amazon_creators": "",
        "amazon_daily": "",
        "amz_sales_deviation_180d": "",
        "ana_data": "",
        "aspire_manual_samples": "",
        "bq_table_meta_data": "",
        "check": "",
        "classified_reviews": "",
        "cogs": "",
        "cogs_calculation_gsheet": "",
        "cogs_calculations_results": "",
        "cogs_calulation_data": "",
        "container_processing_collections_pivot": "",
        "container_processing_view": "",
        "container_processing_view_old": "",
        "creators_connections_rep": "",
        "creators_pivot_view": "",
        "daily_targets": "",
        "daily_targets_high_level": "",
        "date_range_all_countries": "",
        "date_range_business_report": "",
        "date_range_depr_view": "",
        "date_range_report_test": "",
        "date_range_summary_v2": "",
        "deals_group": "",
        "dictionary": "",
        "dictionary_fbm_missed": "",
        "dictionary_inv_statuses_hist": "",
        "dictionary_items_in_box": "",
        "driven_promo_revenue": "",
        "driven_promo_view": "",
        "dsp_direct_spend": "",
        "dsp_total_spend": "",
        "events_calendar": "",
        "fba_inv_missed_dates": "",
        "fba_inventory_partitioned": "",
        "fba_storage_fees_calculation_data": "",
        "flags_iso": "",
        "giveaway_expenses": "",
        "giveaway_revenue": "",
        "influencers_expenses": "",
        "large_orders": "",
        "ld_order_details": "",
        "ld_order_details_all_orders": "",
        "lightning_deals": "",
        "lightning_deals_report": "",
        "lightning_deals_view": "",
        "lost_prevented_overstock_products": "",
        "lost_sales": "",
        "lost_sales_full_data": "",
        "lost_sales_hist": "",
        "lost_sales_v2": "",
        "lost_sales_v3_data": "",
        "maverickx_daily": "",
        "meta_fb_posts_hist": "",
        "meta_fb_posts_hist_2": "",
        "meta_instagram_post_hist": "",
        "overstock_products": "",
        "performance_summary": "",
        "pivot_sales_180d_by_ch": "",
        "prices_history": "",
        "product_cost_hist": "",
        "sales_and_returns_allorders_view": "",
        "samples_pivot": "",
        "samples_provided_to_influencers": "",
        "samples_with_shipping_cost": "",
        "scorecard_general_measures": "",
        "sellecloud_transit_to_wh": "",
        "storage_fees_addition": "",
        "storage_fees_amz_estim_and_plan": "",
        "storage_fees_fba_inv_planning": "",
        "storefront_insights_view": "",
        "storefront_pages_mapper": "",
        "target_wos_by_sku": "",
        "targets": "",
        "targets_calc": "",
        "targets_calc_all_channels": "",
        "tiktok_orders": "",
        "update_freq_norms": "",
        "walmart_restock": "",
        "walmart_restock_2": "",
        "zendesk": "",
    },
    "ebay": {
        "orders": "",
        "payout": "",
        "promoted_listings_general": "",
        "promoted_listings_priority": "",
        "transactions": "",
    },
    "facebook": {
        "attribution_facebook": "",
        "facebook_posts": "",
        "facebook_posts_copy": "",
        "insights": "",
        "instagram_posts": "",
    },
    "google": {
        "ads_report": "",
        "conversions_report": "",
        "google_vs_pinterest": "",
        "google_vs_pinterest_": "",
    },
    "hurma": {
        "candidates": "",
        "careers": "",
        "clickup_candidates": "",
        "clickup_contact_list": "",
        "clickup_job_posting": "",
        "clickup_pto_calendar": "",
        "departments": "",
        "employees": "",
        "employees_archive": "",
        "out_off_office": "",
        "stages": "",
        "teams": "",
        "temp_workers": "",
        "temp_workers_pb": "",
        "tenure": "",
        "vacancies": "",
    },
    "klaviyo": {"campaign_values": "", "campaigns_details": "", "flow_series": ""},
    "kustomer": {"diff_report": ""},
    "levanta": {
        "brands": "",
        "brb_reports": "",
        "click_reports": "",
        "creators": "",
        "products": "",
        "summary_performance": "",
        "test_groups": "",
    },
    "lookerstudio_ds": {"ana_meta_tracker": "", "meta_marketing_insights": ""},
    "pinterest": {"ads_analytics": ""},
    "reports": {
        "AdvertisedProduct": "",
        "PurchasedProduct": "",
        "SponsoredBrandsPlacement": "",
        "SponsoredDisplay": "",
        "SponsoredProductsPlacement": "",
        "active_listing_report": "",
        "aged_inventory_surcharge": "",
        "all_listing_report": "",
        "all_orders": "A table with all orders information for Amazon, including off-amazon sales which were fulfilled by Amazon",
        "all_orders_usd": "",
        "attribution": "",
        "awd_inventory": "",
        "awd_shipments": "",
        "awd_shipments_details": "",
        "business_report": "",
        "business_report_asin": "",
        "date_range_report": "",
        "dictionary": "",
        "dsp_report": "",
        "exchange_rates": "",
        "fba_inventory": "",
        "fba_inventory_partitioned": "",
        "fba_inventory_planning": "Main table containing all necessary inventory information for multiple Amazon marketplaces",
        "fba_inventory_planning_copy": "",
        "fba_returns": "",
        "fee_preview": "",
        "fee_preview_usd": "",
        "fulfilled_inventory": "",
        "inventory": "",
        "profitability": "",
        "profitability_view": "",
        "promotions": "",
        "reserved_inventory": "",
        "restock_inventory": "",
        "settlement": "",
        "settlement_daily": "",
        "settlement_daily_usd": "",
        "shipments": "Amazon fulfilled orders (excluding FBM shipments), crucial table for building a Promotions report",
        "sponsored_brands_all": "",
        "sponsored_brands_video": "",
        "sponsored_display": "",
        "storage_fee": "",
        "storage_fee_usd": "",
        "store_insights_asin": "",
        "store_insights_date": "",
        "store_insights_pages": "",
    },
    "sellercloud": {
        "fba_shipments": "",
        "fba_shipments_partitioned": "",
        "inventory": "",
        "inventory_bins": "",
        "inventory_bins_partitioned": "",
        "inventory_bins_report": "",
        "inventory_partitioned": "",
        "orders": "",
        "purchase_orders": "",
        "purchase_orders_saved_and_pending": "",
        "warehouse_bin_movements": "",
    },
    "shipstation": {
        "samples_shipments": "",
        "samples_shipments_cost": "",
        "shipstation_orders": "",
        "shipstation_orders_temp": "",
        "shipstation_shipments": "",
        "shipstation_stores": "",
        "shipstation_tags": "",
    },
    "shopify": {
        "abandoned_checkouts": "",
        "customers": "",
        "ebay_vs_shopify": "",
        "inventory": "",
        "ordered_products": "",
        "orders": "",
    },
    "skai": {
        "campaigns_info": "",
        "campaigns_performance": "",
        "campaigns_performance_v2": "",
    },
    "slack": {"users_list": ""},
    "supply_chain": {
        "aged_inventory_surcharge": "",
        "awd_inventory": "",
        "awd_shipments": "",
        "awd_shipments_details": "",
        "business_report": "",
        "fba_inventory": "",
        "manage_fba_Inventory": "",
        "monthly_storage_fee": "",
        "reserved_inventory": "",
        "restock_inventory": "",
        "sellercloud_fba_shipments": "",
        "sellercloud_fba_shipments_partitioned": "",
        "sellercloud_inventory": "",
        "sellercloud_inventory_bins": "",
        "sellercloud_inventory_bins_partitioned": "",
        "sellercloud_inventory_partitioned": "",
        "sellercloud_orders": "",
        "sellercloud_purchase_orders": "",
        "sellercloud_wh_bin_movements": "",
    },
    "target": {
        "financial_reconciliation": "",
        "orders": "",
        "returns": "",
        "returns_details": "",
    },
    "tiktok": {
        "attribution_tiktok": "",
        "campaign_metrics": "",
        "gmv_max_metrics": "",
        "orders": "",
        "returns": "",
        "sku_duplicates": "",
        "states_dict": "",
        "tiktok_fba_finder": "",
        "tiktok_fin_view_bi": "",
        "tiktok_fin_view_bi_2": "",
        "tiktok_finance_report": "",
        "tiktok_finance_report_2": "",
        "tiktok_order_temp": "",
        "tiktok_shipping": "",
        "tiktok_shipping_cost": "",
    },
    "walmart": {
        "inventory": "",
        "inventory_wfs": "",
        "legacy_payments": "",
        "legacy_payments_tmp": "",
        "orders": "",
        "orders_total": "",
        "payments": "",
        "payments_tmp": "",
        "returns": "",
        "summary": "",
    },
    "zenefits": {
        "employments": "",
        "out_off_office": "",
        "people": "",
        "people_and_employments": "",
    },
}
